name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: nikolodion/cmake-tdd:latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      # Configure CMake in a 'build' subdirectory.
      run: mkdir build && cd build && cmake .. 

    - name: Build
      # Build your program with the given configuration
      working-directory: ${{github.workspace}}/build
      run: make

    - name: Test
      # Execute tests defined by the CMake configuration.
      working-directory: ${{github.workspace}}/build
      run: make test

    - name: Check
      # Execute checks with CppCheck.
      working-directory: ${{github.workspace}}/build
      run: make check

    - name: Doc
      # Generate documentation with doxygen.
      working-directory: ${{github.workspace}}/build
      run: make doc

    - name: Rsync
      run: apt-get update && apt-get install -y rsync
    - name: Pages
      # Publish doxygen documentation
      
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: main
        folder: ${{github.workspace}}/build/doc/html
