name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: nikolodion/cmake-tdd:latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      # Configure CMake in a 'build' subdirectory.
      run: mkdir build && cd build && cmake .. 

    - name: Build
      # Build your program with the given configuration
      working-directory: ${{github.workspace}}/build
      run: make

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      run: make test

    - name: Check
      working-directory: ${{github.workspace}}/build
      # Execute checks with CppCheck.
      run: make check
      
